server:
  servlet:
    context-path: "/api"
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true